manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmk
      revision: v0.3.0
      path: zmk

    - name: zephyr
      remote: zmk
      revision: v0.3.0
      path: zephyr

    - name: zmk-config
      path: config

  self:
    path: config
