identifier: lily58_joao
name: Lily58 Joao Custom Shield
type: shield
compatible: [zmk, split, keyboard]
arch: arm

# Arquivo DTSI da matriz, pinos etc
includes:
  - lily58_joao.dtsi

# O shield possui duas metades
outputs:
  - left
  - right
