name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Show flake info
        run: nix flake show .

      - name: Init west workspace
        run: |
          nix develop --command west init
          nix develop --command west update

      - name: Build Left Side (Feather nRF52840)
        run: |
          nix develop --command west build \
            -s zmk/app \
            -b adafruit_feather_nrf52840 \
            -d build/left \
            -- -DSHIELD=lily58_joao_left -DZMK_CONFIG=$GITHUB_WORKSPACE/config

      - name: Upload Left Firmware
        uses: actions/upload-artifact@v4
        with:
          name: lily58_left_feather
          path: build/left/zephyr/*.uf2

      - name: Build Right Side (Feather nRF52840)
        run: |
          nix develop --command west build \
            -s zmk/app \
            -b adafruit_feather_nrf52840 \
            -d build/right \
            -- -DSHIELD=lily58_joao_right -DZMK_CONFIG=$GITHUB_WORKSPACE/config

      - name: Upload Right Firmware
        uses: actions/upload-artifact@v4
        with:
          name: lily58_right_feather
          path: build/right/zephyr/*.uf2
