name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            ninja-build \
            g++ \
            cmake \
            wget \
            unzip

      - name: Install west
        run: pip3 install west

      - name: Initialize west workspace
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build LEFT
        run: |
          west build -s zmk/app -d build/left -b adafruit_feather_nrf52840 \
            -- -DSHIELD=lily58_joao_left -DZMK_CONFIG=$GITHUB_WORKSPACE/config

      - name: Upload LEFT
        uses: actions/upload-artifact@v4
        with:
          name: lily58_left
          path: build/left/zephyr/*.uf2

      - name: Build RIGHT
        run: |
          west build -s zmk/app -d build/right -b adafruit_feather_nrf52840 \
            -- -DSHIELD=lily58_joao_right -DZMK_CONFIG=$GITHUB_WORKSPACE/config

      - name: Upload RIGHT
        uses: actions/upload-artifact@v4
        with:
          name: lily58_right
          path: build/right/zephyr/*.uf2
