name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Init + Update + Build (Left + Right)
        run: |
          nix develop --command bash -c "
            echo '--- INITIALIZING WEST WORKSPACE ---'
            west init -l config
            west update

            echo '--- BUILDING LEFT SIDE ---'
            west build \
              -s zmk/app \
              -b adafruit_feather_nrf52840 \
              -d build/left \
              -- -DSHIELD=lily58_joao_left -DZMK_CONFIG=$GITHUB_WORKSPACE/config

            echo '--- BUILDING RIGHT SIDE ---'
            west build \
              -s zmk/app \
              -b adafruit_feather_nrf52840 \
              -d build/right \
              -- -DSHIELD=lily58_joao_right -DZMK_CONFIG=$GITHUB_WORKSPACE/config
          "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: |
            build/left/zephyr/*.uf2
            build/right/zephyr/*.uf2
